# See https://pre-commit.com for more information.
# Install the git hook with: pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: cargo-fmt-nightly
        name: cargo +nightly fmt
        description: Format Rust code (including doc comments) with the nightly formatter.
        entry: cargo +nightly fmt
        args: ["--", "--config-path=nightly_rustfmt.toml"]
        language: system
        types: [rust]
        pass_filenames: false
